#!/bin/bash

# Stop on error
set -e

# modules to be build
MODULES=$1;
# directory in which build request will be served
PROJECT_NAME=$2;

# Current directory
DIR=`pwd`;

echo "test" > ${DIR}/build.log;

echo "Project = ${PROJECT_NAME}" >> ${DIR}/build.log;
echo "Modules = ${MODULES}" >> ${DIR}/build.log;

echo "cd to ./vendors/${PROJECT_NAME}" >> ${DIR}/build.log;
cd ./vendors/${PROJECT_NAME} >> ${DIR}/build.log;

echo "Removing ./out/_build/*" >> ${DIR}/build.log;
rm -rf ./out/_build/* >> ${DIR}/build.log;

echo "Removing build.zip" >> ${DIR}/build.log;
rm -rf build.zip >> ${DIR}/build.log;

echo "webpack building ${MODULES}" >> ${DIR}/build.log;
./node_modules/.bin/webpack --env.modules=${MODULES} --env.minify=true --env.ie8=true >> ${DIR}/build.log;

echo "Lists out ./out/_build/*" >> ${DIR}/build.log;
ls -la out/_build >> ${DIR}/build.log;

cd out;
rm -rf package/
mkdir package/
cp _build/*.js package/
zip -r package.zip package/;
