module.exports = exports = {
  // Charts
  Column2D: '../mantle/renderer-javascript/charts/fusioncharts.column2d',
  // Column3D: '../mantle/renderer-javascript/charts/fusioncharts.column3d',
  Bar2D: '../mantle/renderer-javascript/charts/fusioncharts.bar2d',
  // Bar3D: '../mantle/renderer-javascript/charts/fusioncharts.bar3d',
  Area2D: '../mantle/renderer-javascript/charts/fusioncharts.area2d',
  Line: '../mantle/renderer-javascript/charts/fusioncharts.line',
  Pareto2D: '../mantle/renderer-javascript/charts/fusioncharts.pareto2d',
  // Pareto3D: '../mantle/renderer-javascript/charts/fusioncharts.pareto3d',
  Pie2D: '../mantle/renderer-javascript/charts/fusioncharts.pie2d',
  Pie3D: '../mantle/renderer-javascript/charts/fusioncharts.pie3d',
  Doughnut2D: '../mantle/renderer-javascript/charts/fusioncharts.doughnut2d',
  Doughnut3D: '../mantle/renderer-javascript/charts/fusioncharts.doughnut3d',
  MSColumn2D: '../mantle/renderer-javascript/charts/fusioncharts.mscolumn2d',
  // MSColumn3D: '../mantle/renderer-javascript/charts/fusioncharts.mscolumn3d',
  MSBar2D: '../mantle/renderer-javascript/charts/fusioncharts.msbar2d',
  // MSBar3D: '../mantle/renderer-javascript/charts/fusioncharts.msbar3d',
  MSArea: '../mantle/renderer-javascript/charts/fusioncharts.msarea',
  MSLine: '../mantle/renderer-javascript/charts/fusioncharts.msline',
  StackedArea2D: '../mantle/renderer-javascript/charts/fusioncharts.stackedarea2d',
  StackedColumn2D: '../mantle/renderer-javascript/charts/fusioncharts.stackedcolumn2d',
  // StackedColumn3D: '../mantle/renderer-javascript/charts/fusioncharts.stackedcolumn3d',
  StackedBar2D: '../mantle/renderer-javascript/charts/fusioncharts.stackedbar2d',
  // StackedBar3D: '../mantle/renderer-javascript/charts/fusioncharts.stackedbar3d',
  // Marimekko: '../mantle/renderer-javascript/charts/fusioncharts.marimekko',
  MSStackedColumn2D: '../mantle/renderer-javascript/charts/fusioncharts.msstackedcolumn2d',
  MSCombi2D: '../mantle/renderer-javascript/charts/fusioncharts.mscombi2d',
  // MSCombi3D: '../mantle/renderer-javascript/charts/fusioncharts.mscombi3d',
  // MSColumnLine3D: '../mantle/renderer-javascript/charts/fusioncharts.mscolumnline3d',
  StackedColumn2DLine: '../mantle/renderer-javascript/charts/fusioncharts.stackedcolumn2dline',
  // StackedColumn3DLine: '../mantle/renderer-javascript/charts/fusioncharts.stackedcolumn3dline',
  MSCombidy2D: '../mantle/renderer-javascript/charts/fusioncharts.mscombidy2d',
  // MSColumn3DLineDy: '../mantle/renderer-javascript/charts/fusioncharts.mscolumn3dlinedy',
  // StackedColumn3DLineDy: '../mantle/renderer-javascript/charts/fusioncharts.stackedcolumn3dlinedy',
  MSStackedColumn2DLineDy: '../mantle/renderer-javascript/charts/fusioncharts.msstackedcolumn2dlinedy',
  ScrollColumn2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollcolumn2d',
  ScrollStackedColumn2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollstackedcolumn2d',
  ScrollArea2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollarea2d',
  ScrollLine2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollline2d',
  ScrollCombi2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollcombi2d',
  ScrollCombiDy2D: '../mantle/renderer-javascript/charts/fusioncharts.scrollcombidy2d',
  Scatter: '../mantle/renderer-javascript/charts/fusioncharts.scatter',
  Bubble: '../mantle/renderer-javascript/charts/fusioncharts.bubble',

  // PowerCharts
  DragColumn: '../mantle/renderer-javascript/charts/fusioncharts.dragcolumn2d.js',
  DragArea: '../mantle/renderer-javascript/charts/fusioncharts.dragarea.js',
  DragLine: '../mantle/renderer-javascript/charts/fusioncharts.dragline.js',
  DragNode: '../mantle/renderer-javascript/charts/fusioncharts.dragnode.js',
  LogMSColumn2d: '../mantle/renderer-javascript/charts/fusioncharts.logmscolumn2d.js',
  LogStackedColumn2d: '../mantle/renderer-javascript/charts/fusioncharts.logstackedcolumn2d.js',
  LogMSLine: '../mantle/renderer-javascript/charts/fusioncharts.logmsline.js',
  InverseMSColumn2d: '../mantle/renderer-javascript/charts/fusioncharts.inversemscolumn2d.js',
  InverseMSLine: '../mantle/renderer-javascript/charts/fusioncharts.inversemsline.js',
  InverseMSArea: '../mantle/renderer-javascript/charts/fusioncharts.inversemsarea.js',
  ErrorBar2D: '../mantle/renderer-javascript/charts/fusioncharts.errorbar2d.js',
  ErrorLine: '../mantle/renderer-javascript/charts/fusioncharts.errorline.js',
  ErrorScatter: '../mantle/renderer-javascript/charts/fusioncharts.errorscatter.js',
  MSStepline: '../mantle/renderer-javascript/charts/fusioncharts.msstepline.js',
  SelectScatter: '../mantle/renderer-javascript/charts/fusioncharts.selectscatter.js',
  Spline: '../mantle/renderer-javascript/charts/fusioncharts.spline.js',
  SplineArea: '../mantle/renderer-javascript/charts/fusioncharts.splinearea.js',
  MSSpline: '../mantle/renderer-javascript/charts/fusioncharts.msspline.js',
  MSSplineDy: '../mantle/renderer-javascript/charts/fusioncharts.mssplinedy.js',
  MSSplineArea: '../mantle/renderer-javascript/charts/fusioncharts.mssplinearea.js',
  MultilevelPie: '../mantle/renderer-javascript/charts/fusioncharts.multilevelpie.js',
  Kagi: '../mantle/renderer-javascript/charts/fusioncharts.kagi.js',
  WaterFall2D: '../mantle/renderer-javascript/charts/fusioncharts.waterfall2d.js',
  HeatMap: '../mantle/renderer-javascript/charts/fusioncharts.heatmap.js',

  // Widgets
  Bulb: '../mantle/renderer-javascript/charts/fusioncharts.bulb',
  Hlineargauge: '../mantle/renderer-javascript/charts/fusioncharts.hlineargauge',
  Vbullet: '../mantle/renderer-javascript/charts/fusioncharts.vbullet',
  Hbullet: '../mantle/renderer-javascript/charts/fusioncharts.hbullet',
  Vled: '../mantle/renderer-javascript/charts/fusioncharts.vled',
  Hled: '../mantle/renderer-javascript/charts/fusioncharts.hled',
  Thermometer: '../mantle/renderer-javascript/charts/fusioncharts.thermometer',
  Cylinder: '../mantle/renderer-javascript/charts/fusioncharts.cylinder',
  Funnel: '../mantle/renderer-javascript/charts/fusioncharts.funnel',
  Pyramid: '../mantle/renderer-javascript/charts/fusioncharts.pyramid',
  SparkColumn: '../mantle/renderer-javascript/charts/fusioncharts.sparkcolumn',
  SparkWinLoss: '../mantle/renderer-javascript/charts/fusioncharts.sparkwinloss',
  SparkLine: '../mantle/renderer-javascript/charts/fusioncharts.sparkline',
  RealtimeColumn: '../mantle/renderer-javascript/charts/fusioncharts.realtimecolumn',
  RealtimeArea: '../mantle/renderer-javascript/charts/fusioncharts.realtimearea',
  RealtimeLine: '../mantle/renderer-javascript/charts/fusioncharts.realtimeline',
  RealtimeStackedArea: '../mantle/renderer-javascript/charts/fusioncharts.realtimestackedarea',
  RealtimeStackedColumn: '../mantle/renderer-javascript/charts/fusioncharts.realtimestackedcolumn',
  RealtimeLineDy: '../mantle/renderer-javascript/charts/fusioncharts.realtimelinedy',
  AngularGauge: '../mantle/renderer-javascript/charts/fusioncharts.angulargauge',

  // Transcoders
  XMLTranscoder: '../mantle/updater/xml-transcoder',
  JSONTranscoder: '../mantle/updater/json-transcoder',
  IgnoreCaseExt: '../mantle/updater/ignore_case_ext',
  ThemeEngine: '../crust/themes/themes',
  DefaultTheme: '../crust/themes/themes.default',
  ToolTipController: '../mantle/renderer-javascript/redraphael/tooltip-controller',
  ToolTipAdapter: '../mantle/renderer-javascript/redraphael/tooltip-adapter',

  // VML
  VML: '../mantle/renderer-javascript/redraphael/redraphael.vml'
};
